// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// \`\`\`dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// \`\`\`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYyLfFG9E7v8zRcleO1qLipYNvB5iejQ',
    appId: '1:212278460454:web:e70ec7214c754c8cc2e6e7',
    messagingSenderId: '212278460454',
    projectId: 'bemaker-scanner',
    authDomain: 'bemaker-scanner.firebaseapp.com',
    storageBucket: 'bemaker-scanner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWuCBqYVZtENQRzI4sK4eODKb_1x6w2FA',
    appId: '1:212278460454:android:dd190be9016f0e8ac2e6e7',
    messagingSenderId: '212278460454',
    projectId: 'bemaker-scanner',
    storageBucket: 'bemaker-scanner.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw2oxw3erdbHhOaQvm2jjT6EdNPoiwqG4',
    appId: '1:212278460454:ios:d1ba5ade1dd63d25c2e6e7',
    messagingSenderId: '212278460454',
    projectId: 'bemaker-scanner',
    storageBucket: 'bemaker-scanner.firebasestorage.app',
    iosBundleId: 'com.example.flutterScanner',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'INSERT_YOUR_MACOS_API_KEY_HERE',
    appId: '1:1234567890:ios:1234567890',
    messagingSenderId: '1234567890',
    projectId: 'flutter-scanner-demo',
    storageBucket: 'flutter-scanner-demo.appspot.com',
    iosBundleId: 'com.example.flutterScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'INSERT_YOUR_WINDOWS_API_KEY_HERE',
    appId: '1:1234567890:web:1234567890',
    messagingSenderId: '1234567890',
    projectId: 'flutter-scanner-demo',
    authDomain: 'flutter-scanner-demo.firebaseapp.com',
    storageBucket: 'flutter-scanner-demo.appspot.com',
  );
}
